### PR TITLE
Feature: Added support for custom fonts and and text alignment (on Android)

### PR DESCRIPTION
**Pull request by itchingpixels**

### CODE REVIEW

**Comment by prscX** [comment]
Thanks a lot @itchingpixels for sharing the PR and effort. I have merged the same.

Are you using this library on iOS platform as well? If yes do you have any plans of enabling `font` & `textAlign` prop on iOS as well?

Thanks
</ Pranav >

**Comment by itchingpixels** [comment]
Yes, we'll do that:) I'd maybe advise you to not to release this until we get that done, it may have unintended side effects.

**Comment by itchingpixels** [comment]
the ETA is 1-2 days

**Comment by prscX** [comment]
Thanks @itchingpixels. Let me know incase any support/help is required.

Thanks
</ Pranav >

**Pull request merged**
